FROM java:8
EXPOSE 8080
ADD cron-tz-emails-scheduler/target/cron-tz-emails-scheduler-0.0.1-SNAPSHOT.jar cron-tz-emails-scheduler-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","cron-tz-emails-scheduler-0.0.1-SNAPSHOT.jar"]